- apps/templates/home/dashboard.html
> Dashboard Changes

- apps/templates/home/dashboard.html
> Dashboard Fix

- apps/home/forms.py
- apps/home/urls.py
- apps/home/views.py
- apps/templates/home/add-plant.html
- apps/templates/home/settings.html
Reverts manirajpandian/uvb-light-system#13
> Revert "Zdev l 20 11"

- README.md
- apps/home/forms.py
- apps/home/views.py
- apps/templates/home/add-plant.html
- apps/templates/home/settings.html
Plant fully completed
1. Add plant
2. Edit plant
3. List plant
4. Delete plant
5. Pagination
6. Error Messages
7. Data validation while adding the plant details
> Plant Completed

- apps/home/admin.py
- apps/home/forms.py
- apps/home/models.py
- apps/home/urls.py
- apps/home/views.py
- apps/templates/home/LED-control.html
- apps/templates/home/add-house.html
Add house and Led control display alone
> add house and led control display

- apps/home/urls.py
- apps/home/views.py
- apps/templates/home/dashboard.html
- apps/templates/home/house-list.html
> Delete house and Dashboard

- apps/home/views.py
- apps/templates/home/add-house.html
> Add house full

- apps/home/forms.py
- apps/home/views.py
- apps/templates/home/add-house.html
- apps/templates/home/add-plant.html
> house error msg

- apps/home/models.py
- apps/home/views.py
> "29/11 mqtt"

- apps/home/views.py
- apps/templates/home/LED-control.html
- apps/templates/home/dashboard.html
- apps/templates/includes/sidebar.html
Super admin dashboard display, other sidebar display in super admin, all access to super admin, plant setting for only super admin.
> Bug Fix 01_12, super admin display

- apps/home/views.py
- core/settings.py
-LED Deactivate functionalities for house and farm with mqtt
> "1/11 - farm & house delete"

- apps/home/views.py
- apps/templates/home/add-plant.html
- apps/templates/home/page-403.html
- apps/templates/home/page-404.html
- apps/templates/home/page-500.html
Error pages - 404,403,500 in japanese
> 404, 403, 500 pages in japanese

- apps/templates/home/LED-control.html
> led control footer bug fixed

- apps/authentication/views.py
- apps/home/views.py
- apps/templates/accounts/change_password.html
- apps/templates/home/add-house.html
- apps/templates/home/add-plant.html
- apps/templates/home/page-500.html
- apps/templates/home/settings.html
> japanese correction

- apps/home/views.py
- apps/templates/home/house-list.html
04_12 super admin house list fix
> 04_12 super admin house list fix

- apps/home/views.py
- apps/templates/home/dashboard.html
- apps/templates/home/house-list.html
> dashboard correction 04_12

- apps/home/forms.py
- apps/home/views.py
- apps/templates/home/add-plant.html
- apps/templates/home/farm_list.html
- apps/templates/home/house-list.html
- apps/templates/home/settings.html
Farm and Plant super admin login bug fixes.
> Farm and Plant bug fixes

- apps/home/views.py
- apps/templates/home/LED-control.html
- apps/templates/home/dashboard.html
- apps/templates/home/farm_list.html
- apps/templates/home/farmer-list.html
- apps/templates/home/house-list.html
Company name in the filter, in all pages.
> Company filter

- apps/home/views.py
- apps/templates/home/dashboard.html
- apps/templates/home/house-list.html
> bug fixes 08_12

- apps/home/views.py
- apps/templates/home/LED-control.html
-remove unwanted comments and change error message in Japanese .
- add the button disable and history disable during the raspberry is not connected to that LED.
> ”review and changes in led  ctl error ”

- apps/authentication/models.py
- apps/home/views.py
- apps/templates/home/LED-control.html
- apps/templates/home/add-house.html
- apps/templates/home/dashboard.html
- apps/templates/home/farm_list.html
- apps/templates/home/house-list.html
> Multi user for house

- apps/authentication/models.py
- apps/home/views.py
- apps/templates/home/LED-control.html
- apps/templates/home/house-list.html
> led id changes, model changes

- apps/home/views.py
- apps/templates/home/add-house.html
- apps/templates/home/house-list.html
> add_house changes
